#!/usr/bin/env bash

# A Git pre-commit hook for scanning sensitive data in files.

green='\033[0;32m'
red='\033[0;31m'
no_color='\033[0m'

echo "Scanning for sensitive data..."
ahjo-scan.exe --stage --files "^.*"
exit_status=$?

if [ $exit_status -eq 1 ]; then
    echo "If you want to ignore the scan results, add matches to ahjo_scan_ignore.yaml. Otherwise fix the issues and try again."
    echo -e "${red}Commit aborted.${no_color}"
    exit 1
elif [ $exit_status -eq 0 ]; then
    echo -e "${green}Scan check passed.${no_color}\n"
    exit 0
else
    exit 0
fi